# Generated by Django 6.0.2 on 2026-03-01 09:22

from django.db import migrations


import os
from django.contrib.auth.hashers import make_password

def create_default_admin(apps, schema_editor):
    Student = apps.get_model('users', 'Student')
    
    admin_id = os.getenv('ADMIN_STUDENT_ID', 'admin')
    admin_pass = os.getenv('ADMIN_PASSWORD', 'admin123')
    
    if not Student.objects.filter(student_id=admin_id).exists():
        Student.objects.create(
            username=admin_id,
            student_id=admin_id,
            password=make_password(admin_pass),
            is_admin_user=True,
            is_staff=True,
            is_superuser=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_admin),
    ]
